version: '3'
services:
  bd:
    container_name: postgres-microservicio
    image: postgres
    ports:
      - 5434:5432
  personas:
    container_name: personas_contenedor
    image: deisylh/ubuntu-basic
    ports: 
     - 9292:8080
    depends_on:
      - bd
