version: '3'
services:
  personas:
    container_name: personas_contenedor
    image: mokanime/img_personas
    ports: 
     - 9292:8080
    environment:
     - POSTGRES_URL=jdbc:postgresql://46.183.113.254:5432/postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=
